name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release-amd64:
    runs-on: ubuntu-24.04
    env:
      ARCH: "amd64"
      PLATFORM: "linux"
      NAME: "dnsMasqAPI"
      ARTIFACT_DIR: "dist/artifacts"
      ARCHIVE_NAME: "dnsMasqAPI-${{ github.ref_name }}-linux-amd64"
      ARCHIVE_PATH: "dist/artifacts/dnsMasqAPI-${{ github.ref_name }}-linux-amd64.tar.gz"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Build
        run: make build

      - name: Package
        run: |
          # Create ENV file
          mkdir dist
          echo "ARCHIVE_NAME=\"${{ env.ARCHIVE_NAME }}\"" > dist/envvar.sh
          echo "ARTIFACT_DIR=\"${{ env.ARTIFACT_DIR }}\"" >> dist/envvar.sh
          echo "ARCHIVE_PATH=\"${{ env.ARCHIVE_PATH }}\"" >> dist/envvar.sh
          echo "GITHUB_REF=\"${{ github.ref_name }}\"" >> dist/envvar.sh
          echo "PLATFORM=\"${{ env.PLATFORM }}\"" >> dist/envvar.sh
          echo "ARCH=\"${{ env.ARCH }}\"" >> dist/envvar.sh
          
          # Run packaging script
          bash scripts/package.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            Initial Release of this Repo!!

      - name: Upload Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARCHIVE_PATH }}
          asset_name: ${{ env.ARCHIVE_NAME }}.tar.gz
          asset_content_type: application/octet-stream

      - name: Upload Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARTIFACT_DIR }}/install.sh
          asset_name: install.sh
          asset_content_type: application/octet-stream

      - name: Upload Checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARTIFACT_DIR }}/sha256sum-${{ env.PLATFORM }}-${{ env.ARCH }}.txt
          asset_name: sha256sum-${{ env.PLATFORM }}-${{ env.ARCH }}.txt
          asset_content_type: application/octet-stream
