name: Test

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy && go mod download && go get -t

      - name: Run Lint
        run: make lint

      - name: Run Vet
        run: make vet

      - name: Run Tests with Coverage
        run: make coverage | tee coverage_report.log